FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    qemu-system-x86 \
    ovmf \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
COPY ./build/MFTAH.* /work/
COPY mftah.cfg* /work/

RUN cp -f /usr/share/OVMF/OVMF_VARS.fd /work/OVMF_VARS.fd

CMD [ \
    "qemu-system-x86_64", \
    "-drive", "file=fat:rw:/work/hda1,format=raw,if=ide", \
    "-drive", "if=pflash,format=raw,unit=0,file=/usr/share/OVMF/OVMF_CODE.fd,readonly=on", \
    "-drive", "if=pflash,format=raw,unit=1,file=/work/OVMF_VARS.fd", \
    "-m", "256M", \
    "-net", "none", \
    "-smp", "cpus=4,sockets=1,cores=4,threads=1", \
    "-cpu", "max", \
    "-serial", "stdio", \
    "-display", "none", \
    "-debugcon", "file:/work/logs/debug.log", \
    "-global", "isa-debugcon.iobase=0x402" \
]
